# Generated by Django 3.1.1 on 2020-09-25 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_somemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SomeModel',
        ),
    ]
